<?php

define('ROLE_ANONYMOUS', "ROLE_ANONYMOUS");
define('ROLE_USER', "ROLE_USER");
define('ROLE_ADMIN', "ROLE_ADMIN");
define('ROLE_SUPER_ADMIN', "ROLE_SUPER_ADMIN");
define('ROLE_MEGA_ADMIN', "ROLE_MEGA_ADMIN");

define('ROLES_HIERARCHY', [
    ROLE_USER => ROLE_ANONYMOUS,
    ROLE_ADMIN => ROLE_USER,
    ROLE_SUPER_ADMIN => ROLE_ADMIN,
    ROLE_MEGA_ADMIN => ROLE_SUPER_ADMIN,
]);